import { describe, it, expect } from 'vitest';
import { parseCredentialIni } from '../../../src/scanner/credentialIni';
import { toIni } from '../../../src/export/index';
import type { DiscoveryResult } from '../../../src/types';

const SAMPLE = `; Generated by Redis Discovery from scan results.
; Fill in username/password (and ca_cert/client_cert/client_key for mTLS)
; before running osstats against these targets.

[10.0.0.1:6379]
host        = 10.0.0.1
port        = 6379
tls         = false
; Username in case ACL access in enabled
username    = alice
; Password that applies either in db or user (ACL)
password    = secret
; ca_cert     = /path/to/ca.crt
; client_cert = /path/to/client.crt
; client_key  = /path/to/client.key

[10.0.0.2:6380]
host        = 10.0.0.2
port        = 6380
tls         = true
username    =
password    =
`;

describe('parseCredentialIni', () => {
  it('parses host, port, username, password from a section', () => {
    const { rows, errors } = parseCredentialIni(SAMPLE);
    expect(errors).toEqual([]);
    expect(rows).toEqual([
      { host: '10.0.0.1', port: 6379, username: 'alice', password: 'secret' },
      { host: '10.0.0.2', port: 6380, username: undefined, password: undefined },
    ]);
  });

  it('treats a blank username and password as undefined, not empty strings', () => {
    const { rows } = parseCredentialIni(
      '[x]\nhost = 10.0.0.1\nport = 6379\nusername = \npassword = \n',
    );
    expect(rows).toEqual([
      { host: '10.0.0.1', port: 6379, username: undefined, password: undefined },
    ]);
  });

  it('ignores commented-out lines, including ones shaped like key = value', () => {
    const { rows } = parseCredentialIni(
      '[x]\nhost = 10.0.0.1\nport = 6379\n; username = commented-out\n; ca_cert = /path\n',
    );
    expect(rows).toEqual([
      { host: '10.0.0.1', port: 6379, username: undefined, password: undefined },
    ]);
  });

  it('also accepts # as a comment prefix, for configparser compatibility', () => {
    const { rows } = parseCredentialIni('[x]\n# a comment\nhost = 10.0.0.1\nport = 6379\n');
    expect(rows).toEqual([
      { host: '10.0.0.1', port: 6379, username: undefined, password: undefined },
    ]);
  });

  it('ignores unrecognized keys like tls without erroring', () => {
    const { rows, errors } = parseCredentialIni('[x]\nhost = 10.0.0.1\nport = 6379\ntls = true\n');
    expect(errors).toEqual([]);
    expect(rows).toEqual([
      { host: '10.0.0.1', port: 6379, username: undefined, password: undefined },
    ]);
  });

  it('trusts the explicit host/port fields over the section header text', () => {
    const { rows } = parseCredentialIni(
      '[totally-unrelated-alias]\nhost = 10.0.0.9\nport = 6379\n',
    );
    expect(rows).toEqual([
      { host: '10.0.0.9', port: 6379, username: undefined, password: undefined },
    ]);
  });

  it('flags a missing host as an error and skips that section, without dropping the rest of the batch', () => {
    const { rows, errors } = parseCredentialIni(
      '[a]\nport = 6379\n\n[b]\nhost = 10.0.0.2\nport = 6380\n',
    );
    expect(rows).toEqual([
      { host: '10.0.0.2', port: 6380, username: undefined, password: undefined },
    ]);
    expect(errors).toEqual(['section 1: missing host']);
  });

  it('flags a non-numeric port as an error', () => {
    const { rows, errors } = parseCredentialIni('[a]\nhost = 10.0.0.1\nport = notaport\n');
    expect(rows).toEqual([]);
    expect(errors).toEqual(['section 1 (10.0.0.1): invalid port "notaport"']);
  });

  it('flags a missing port as an error', () => {
    const { errors } = parseCredentialIni('[a]\nhost = 10.0.0.1\n');
    expect(errors).toEqual(['section 1 (10.0.0.1): invalid port ""']);
  });

  it('flags a port outside 1-65535 as an error', () => {
    const { errors } = parseCredentialIni(
      '[a]\nhost = 10.0.0.1\nport = 0\n\n[b]\nhost = 10.0.0.2\nport = 65536\n',
    );
    expect(errors).toHaveLength(2);
  });

  it('never includes username or password in an error message', () => {
    const { errors } = parseCredentialIni(
      '[a]\nhost = 10.0.0.1\nport = bad\nusername = verysecretuser\npassword = verysecretpassword\n',
    );
    expect(errors[0]).not.toContain('verysecretuser');
    expect(errors[0]).not.toContain('verysecretpassword');
  });

  it('trims whitespace around keys and values', () => {
    const { rows } = parseCredentialIni('[a]\n  host   =   10.0.0.1  \n  port   =   6379  \n');
    expect(rows).toEqual([
      { host: '10.0.0.1', port: 6379, username: undefined, password: undefined },
    ]);
  });

  it('handles the last section terminating at end-of-file, with no trailing section header', () => {
    const { rows } = parseCredentialIni('[a]\nhost = 10.0.0.1\nport = 6379');
    expect(rows).toEqual([
      { host: '10.0.0.1', port: 6379, username: undefined, password: undefined },
    ]);
  });

  it('returns no rows and no errors for empty input', () => {
    expect(parseCredentialIni('')).toEqual({ rows: [], errors: [] });
  });

  it('returns no rows and no errors when there are no sections at all', () => {
    expect(parseCredentialIni('; just a comment\nsome stray text\n')).toEqual({
      rows: [],
      errors: [],
    });
  });

  it('round-trips with toIni(): parses its own export format once credentials are filled in', () => {
    const result: DiscoveryResult = {
      host: '10.0.0.5',
      port: 6379,
      tls: false,
      product: 'redis',
      version: '8.0.0',
      authRequired: false,
      anonymousStatus: 'open',
      authenticatedStatus: 'not_attempted',
      latency: 1,
      inventory: null,
      tlsCertificate: null,
    };
    const exported = toIni([result]);
    // Simulates a user filling in the blank credential fields toIni() leaves,
    // in a text editor, before uploading the file back in.
    const filledIn = exported
      .replace('username    = ', 'username    = opsuser')
      .replace('password    = ', 'password    = opspass');

    const { rows, errors } = parseCredentialIni(filledIn);
    expect(errors).toEqual([]);
    expect(rows).toEqual([
      { host: '10.0.0.5', port: 6379, username: 'opsuser', password: 'opspass' },
    ]);
  });
});
